name: CI Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
        include:
          - os: macos-12
            arch: x86_64
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
    env:
      REPO_URL: https://github.com/stream-labs/desktop.git
      SLOBS_NO_SIGN: true 
      SLOBS_REPORT_TO_SENTRY: false
      CI: true
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Shallow Clone Another Repository
        run: git clone --depth 1 $REPO_URL cloned-repo

      - name: Enable Corepack
        run: corepack enable

      - name: Install Correct Yarn Version
        run: corepack prepare yarn@3.1.1 --activate

      - name: Run Install for Cloned Repo
        run: yarn install
        working-directory: cloned-repo

      - name: Run Compile for Cloned Repo
        run: yarn compile:production
        working-directory: cloned-repo

      - name: Run Package for Cloned Repo
        run: yarn package:mac
        working-directory: cloned-repo
